# Generated by Django 4.0.5 on 2022-07-17 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Деньги')),
                ('all_transactions', models.IntegerField(default=0)),
                ('coll_user', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Buy_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Название')),
                ('category', models.CharField(default=0, max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='DeepLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=250)),
                ('deep_link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.BooleanField(default=False, verbose_name='Верх, если да - true')),
                ('max_users', models.IntegerField(default=4, verbose_name='Максимальное кол-во участников')),
                ('go_money', models.IntegerField(default=0, verbose_name='Номер участника, который получает след выплату')),
                ('col', models.IntegerField(default=0, verbose_name='Кол-во в матрице')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Деньги')),
                ('referral_link', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True, verbose_name='Реферальная ссылка')),
                ('referral_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма полученных средств по реферальной системе')),
                ('missed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Упущенная сумма')),
                ('wallet', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кошелек')),
                ('line_1', models.CharField(blank=True, max_length=150, null=True, verbose_name='First_Line')),
                ('line_2', models.CharField(blank=True, max_length=150, null=True, verbose_name='Second_Line')),
                ('line_3', models.CharField(blank=True, max_length=150, null=True, verbose_name='Third_Line')),
                ('max_card', models.IntegerField(blank=True, default=0, null=True, verbose_name='Максимальная купленная карта(Формат при bronze 6 карта: 06)')),
                ('admin_or', models.BooleanField(default=False, verbose_name='Админ или нет')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(max_length=150, verbose_name='tx_id')),
                ('timestamp', models.IntegerField(verbose_name='timestamp')),
                ('sender', models.CharField(max_length=150, verbose_name='sender')),
                ('receiver', models.CharField(max_length=150, verbose_name='receiver')),
                ('currency', models.CharField(max_length=150, verbose_name='currency')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('fee', models.IntegerField(verbose_name='fee')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('pkey', models.CharField(max_length=150, verbose_name='pkey')),
            ],
        ),
        migrations.CreateModel(
            name='User_in_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_number', models.IntegerField(verbose_name='Номер участника')),
                ('d', models.IntegerField(default=0, verbose_name='Кол-во зачислений')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.buy_card')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.matrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Third_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Третья линия',
            },
        ),
        migrations.CreateModel(
            name='Second_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Вторая линия',
            },
        ),
        migrations.CreateModel(
            name='History_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кол-во')),
                ('card', models.CharField(max_length=150, verbose_name='Номер счета')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('success', models.BooleanField(default=False, verbose_name='Успешность')),
                ('name_operation', models.CharField(choices=[('Output', 'Вывод'), ('Input', 'Ввод')], max_length=50)),
                ('txid', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='First_Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Первая линия',
            },
        ),
        migrations.CreateModel(
            name='Category_Silver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.IntegerField(default=100)),
                ('card_2', models.IntegerField(default=150)),
                ('card_3', models.IntegerField(default=250)),
                ('card_4', models.IntegerField(default=400)),
                ('card_5', models.IntegerField(default=500)),
                ('card_6', models.IntegerField(default=666)),
                ('card_6_disable', models.BooleanField(default=False, verbose_name='Доступ для 6 карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Серебряная категория',
            },
        ),
        migrations.CreateModel(
            name='Category_Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.IntegerField(default=750)),
                ('card_2', models.IntegerField(default=1000)),
                ('card_3', models.IntegerField(default=1250)),
                ('card_4', models.IntegerField(default=1500)),
                ('card_5', models.IntegerField(default=2000)),
                ('card_6', models.IntegerField(default=2222)),
                ('card_6_disable', models.BooleanField(default=False, verbose_name='Доступ для 6 карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Золотая категория',
            },
        ),
        migrations.CreateModel(
            name='Category_Emerald',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.IntegerField(default=2500)),
                ('card_2', models.IntegerField(default=5000)),
                ('card_3', models.IntegerField(default=7500)),
                ('card_4', models.IntegerField(default=10000)),
                ('card_5', models.IntegerField(default=15000)),
                ('card_6', models.IntegerField(default=22222)),
                ('card_6_disable', models.BooleanField(default=False, verbose_name='Доступ для 6 карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Изумрудная категория',
            },
        ),
        migrations.CreateModel(
            name='Category_Bronze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.IntegerField(default=10)),
                ('card_2', models.IntegerField(default=15)),
                ('card_3', models.IntegerField(default=25)),
                ('card_4', models.IntegerField(default=40)),
                ('card_5', models.IntegerField(default=50)),
                ('card_6', models.IntegerField(default=77)),
                ('card_6_disable', models.BooleanField(default=False, verbose_name='Доступ для 6 карты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
            options={
                'verbose_name_plural': 'Бронзовая категория',
            },
        ),
        migrations.AddField(
            model_name='buy_card',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.card'),
        ),
        migrations.AddField(
            model_name='buy_card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Деньги')),
                ('wallet', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кошелек')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Админ',
            },
        ),
    ]
