# Generated by Django 4.0.5 on 2022-07-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_in_matrix',
            name='all_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_in_matrix',
            name='total_wins',
            field=models.IntegerField(default=0),
        ),
    ]
