# Generated by Django 4.0.5 on 2022-07-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_in_matrix_all_wins_user_in_matrix_total_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
