# Generated by Django 4.0.5 on 2022-07-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_all_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_card',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
