# Generated by Django 4.0.5 on 2022-07-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_all_card_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_card',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
