# Generated by Django 4.0.5 on 2022-07-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveBigIntegerField(verbose_name='Id_user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение пользователю')),
                ('user_id', models.CharField(default=0, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Memcache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('memcache', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Bot', models.CharField(max_length=250)),
                ('Chat_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User_Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField(default=0)),
                ('username', models.CharField(default=0, max_length=50, verbose_name='Имя')),
                ('first_name', models.CharField(default=0, max_length=256)),
                ('last_name', models.CharField(default=0, max_length=256)),
                ('language_code', models.CharField(default='ru', help_text="Telegram client's lang", max_length=8)),
                ('deep_link', models.CharField(default=0, max_length=64)),
                ('is_blocked_bot', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
    ]
